import Link from "next/link";
import styles from "../../../styles/Home.module.css";
import Pokegrid from "../../../components/Pokegrid/Pokegrid";
import Head from "next/head";
import Stack from "@mui/material/Stack";
import { Button } from "@mui/material";
import ArrowBackIcon from "@mui/icons-material/ArrowBack";
import { useEffect, useState } from "react";
import { includes } from "lodash";

export default function FavoritesPage({}) {
  const [pokemonJSON, setPokemonJSON] = useState({
    count: 0,
    next: null,
    previous: null,
    results: [],
  });
  const fillMap = { 0: 0, 1: 2, 2: 1 };

  useEffect(() => {
    console.log("CADA RUN DE USE EFFECT");
    const favoriteList = JSON.parse(localStorage.getItem("favoriteList"));
    if (!favoriteList) localStorage.setItem("favoriteList", JSON.stringify([]));

    const tempPokemonJSON = { ...pokemonJSON };

    for (const favorite of favoriteList) {
      const pokeName = favorite;
      const pokeUrl = `https://pokeapi.co/api/v2/pokemon/${pokeName}/`;
      let mustAdd = true;
      console.log(tempPokemonJSON);
      for (const entry of tempPokemonJSON.results) {
        if (entry.name == pokeName) {
          mustAdd = false;
          break;
        }
      }

      if (mustAdd) {
        tempPokemonJSON.results.push({ name: pokeName, url: pokeUrl });
        tempPokemonJSON.count++;
      }
    }
    console.log(tempPokemonJSON);
    setPokemonJSON((pokemonJSON) => ({
      ...pokemonJSON,
      ...tempPokemonJSON,
    }));
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>PokeFavorites</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/pokemon.ico" />
      </Head>
      <div className={styles["pokegrid-header"]}>
        <div>PokeFavorites</div>
      </div>

      <Pokegrid
        pokemonJSON={pokemonJSON}
        pokemonList={pokemonJSON.results}
        remain={3}
        fillMap={fillMap}
      />

      <Stack alignItems="center" sx={{ marginBottom: "2rem" }}>
        <Link href="/">
          <Button
            variant="contained"
            size="large"
            startIcon={<ArrowBackIcon />}
            className={styles["back-btn"]}
            sx={{
              marginTop: "2rem",
              "& .MuiSvgIcon-root": {
                fontSize: "30px !important",
              },
            }}
          >
            Back to home
          </Button>
        </Link>
      </Stack>
    </div>
  );
}
