import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";
import Button from "@mui/material/Button";
import PlayCircleFilledIcon from "@mui/icons-material/PlayCircleFilled";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>PokeLanding</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/pokemon.ico" />
      </Head>

      <a href="https://pinflag.cl/">
        <div className={styles.pinflag}>
          <Image
            src="/pinflag_logo.png"
            alt="pinlogo"
            height={100}
            width={905 / 5.9}
          />
        </div>
      </a>
      <main className={styles.main}>
        <h1 className={`${styles.title} ${styles["black-border"]}`}>
          Welcome to{" "}
          <span className={styles["white-border"]} style={{ color: "#1c2444" }}>
            Pin
          </span>
          <span style={{ color: "#34cccc" }}>Flag</span>
        </h1>
        <h1 className={`${styles.title} ${styles["black-border"]}`}>
          <span style={{ color: "#e64c3c" }}>Poke</span>dex!
        </h1>

        <p className={styles.code}>Get started by pressing the START button</p>

        <Link href="/pokegrid/page/1">
          <Button
            variant="contained"
            size="large"
            endIcon={<PlayCircleFilledIcon />}
            className={styles["start-btn"]}
            sx={{
              "& .MuiSvgIcon-root": {
                fontSize: "36px !important",
              },
            }}
          >
            START
          </Button>
        </Link>

        {/* <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div> */}
      </main>

      <footer className={styles.footer}>
        <div>Made by QueMemo</div>
      </footer>
    </div>
  );
}
